app_url: APPLICATION_URL_HERE
app_name: APPLICATION_NAME_HERE
app_logo: logo.png
app_header_logo: logo.png
auto_approval: false
secret_key_base: SECRET_KEYBASE_HERE
coingecko_url: https://api.coingecko.com/api/v3/simple/price
contract_address:
  erc721: 'ERC721_CONTRACT_ADDRESS_HERE'
rinkeby:
  gasstation_url: https://ethgasstation.info/api/ethgasAPI.json
  base_coin: ETH
  app_coin: WETH
  signer_private_key: SIGNER_PRIVATE_KEY_HERE
  ethereum_provider: https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
  url: 'https://rinkeby.etherscan.io'
matic-test:
  gasstation_url: https://gasstation-mainnet.matic.network/
  base_coin: MATIC
  app_coin: WMATIC
  signer_private_key: SIGNER_PRIVATE_KEY_HERE
  ethereum_provider: https://polygon-rpc.com
  url: 'https://mumbai.polygonscan.com'
etherscan:
  api_key: ETHERSCAN_API_KEY_HERE
  api_url: https://api.etherscan.io/api
pinata:
  api_key: PINATA_API_KEY_HERE
  api_secret: PINATA_API_SECRET_KEY_HERE
  base_url: https://api.pinata.cloud/pinning/pinFileToIPFS
default_fees:
  buyer_service_fee: 2.5
  seller_servicw_fee: 0
discussion_url: '#'
support_url: '#'
opensea_url: https://rinkeby-api.opensea.io
alchemy:
  development:
    baseURL: https://eth-rinkeby.g.alchemy.com
    apiKey: DEV_ALCHAMEY_API_KEY_HERE
  production:
    baseURL: https://eth-mainnet.g.alchemy.com
    apiKey: PRODUCTION_ALCHAMEY_API_KEY_HERE-g9YevOtF
